astrocamp/16th-TripWay

schedles/admin.py
schedles/apps.py
schedles/models.py
schedles/tests.py
schedles/urls.py
schedles/views.py

改分支名稱 -> Schedels

---

.gitignore
core/settings.py
core/urls.py
core/views.py
members/admin.py
members/apps.py
members/forms.py
members/models.py
members/tests.py
members/urls.py
members/views.py
package-lock.json
package.json
tailwind.config.js
templates/layouts/base.html
templates/pages/home.html
templates/registration/login.html
templates/registration/register.html
templates/shared/navbar.html

製作會員系統：登入/登出/註冊
利用django內建User系統作會員系統
有先暫時做個navbar當樣板
1.註冊：註冊後寫進資料庫內
2.登入：比對資料庫資料，正確後登入返回主頁，Login/Signup不見，出現Logout
3.登出：Logout後返回主頁，出現Login/Signup
https://github.com/astrocamp/16th-TripWay/assets/167271345/076df693-ba4d-46f3-a2ec-8ee743509261
密碼設立規則暫時先關閉以便測試
待調整：
目前仍以Username驗證，後續會再修正為以Email驗證
提示訊息待完成

Issue #1 Update Members

---

Makefile
README.md
static/scripts/map.js
static/styles/google.css
templates/layouts/base.html
templates/shared/navbar.html
templates/trips/index.html
templates/trips/map.html
trips/urls.py
trips/views.py

https://github.com/astrocamp/16th-TripWay/assets/162076462/55c97a81-5c77-42b7-8701-13c675375357
`Google Map` 
1. 將 google map 加入 行程列表(trip)
2. google map 新增搜尋後，計算路線花費時間（目前設定為開車模式）
- `Makefile`
拿掉 poetry 避免混亂
- `README.md`
調整 poetry install 順序，放在 shell 之後

新增 google 地圖頁面

---

schedules/views.py
templates/schedules/index.html
templates/shared/navbar.html

https://github.com/astrocamp/16th-TripWay/assets/162015439/24f50075-53da-4a0f-a010-4a32265b0cee
1. 在 schedules/index.html頁面新增日期頁籤功能 (可正確顯示行程天數的日期頁籤，點擊頁籤顯示的景點也會依時間排序）
頁籤部分有使用 groupby函式來按日期進行分組
[itertools.groupby()](https://www.volcengine.com/theme/11051525-A-7-1
待修正：
- 尚未建立景點的日期頁籤變色效果切換異常
- 切換日期頁籤時按新增景點進入後日期欄位不是預設顯示該天日期

issue #25 新增日期頁籤

---

members/models.py
members/urls.py
members/views.py

- model: 增加資料表 MemberSpot，用來多對多關聯會員和景點
- views: 增加會員 index 和把關聯串起來的 add_favorite_spot
- urls: 增加從首頁到 profile 的網址路徑，還未建立 spot_detail 的收藏路徑

Issue #29 更新member的model, views, urls (關聯)

---

core/settings.py
schedules/views.py
src/scripts/app.js
src/scripts/schedules/update.js
src/scripts/trips/new.js
templates/schedules/update.html
templates/trips/new.html

https://github.com/astrocamp/16th-TripWay/assets/162015439/28c5aa23-65ff-4702-908c-ab380e365a0b
1. 修正：trips建立新行程頁面日期欄位選取範圍
-出發日欄位：選擇日期時不可小於建立的當天
-結束日欄位：選擇日期時不可小於出發日
2. 修正：schedules編輯景點頁面離開時間之設定
-離開時間欄位：選擇離開時間時不可早於抵達時間

issue #43 修正-行程日期欄位選取範圍＆景點離開時間之驗證

---

poetry.lock
templates/schedules/index.html
templates/schedules/show.html
templates/schedules/update.html
templates/spots/create.html
templates/spots/spot_detail.html
templates/spots/spot_list.html
templates/trips/index.html
templates/trips/new.html
templates/trips/update.html

**trips/index.html & new.html
schedules/show.html & update.html 
spots/create.html & spot_detail.html & spot_list.html**
- 新增返回上一頁icon及功能
- 將首頁icon連結都統一回到home頁面
schedules/index.html
- 刪除減天數之按鈕
- 刪除 預設顯示第一天頁籤及行程的判斷式

新增返回上一頁icon功能

---

payments/urls.py
payments/views.py
templates/payments/upgrade.html
templates/trips/new_member.html
trips/views.py

1. 調整金流upgrade頁面
2. 調整金流回傳成功畫面為登入狀態

調整金流成功畫面為登入狀態 ＆ 升級頁面調整

---

notifies/views.py
schedules/urls.py
schedules/views.py
src/tailwind.css
static/scripts/notifications.js
tailwind.config.js
templates/notifies/notification_list.html
templates/schedules/index.html
templates/shared/navbar-home.html
templates/shared/navbar-map.html
templates/shared/navbar.html
templates/trips/index.html

https://github.com/astrocamp/16th-TripWay/assets/162015439/b58dc9a7-5378-47af-808c-926706874cc9
**notification_list.html**
- 將 js部分移出html檔，用CDN方式引入
**navbar-home.html 、 navbar-map.html、navbar-home.html**
- 因通知是設置成另外跳轉到通知頁面，不是收合方式呈現，所以刪除多餘內容
**trips/index.html**
- 排序下拉選單新增箭頭符號
**schedules/index.html**
- 更改頁籤css
- 新增刪除一天行程按鈕

Issue #103 更新navbar頁面 & 調整schedules/index 頁籤樣式+新增刪除按鈕

---

members/urls.py
src/scripts/favorite.js
templates/profile/index.html
templates/spots/spot_detail.html

1. 放收藏心心在 profile 頁面，也可以在 profile 頁面取消收藏
2. 把收藏心心改成 TripWay Red
https://github.com/astrocamp/16th-TripWay/assets/74704329/cc53fff2-e471-4f4d-8b0c-c4e720bb9a28

Issue #80 收藏按鈕可以在景點頁面和個人頁面連動 ＆ 收藏改紅色

---

payments/service.py
src/scripts/notice.js

將使用者信箱帶入藍新金流結帳畫面
https://github.com/astrocamp/16th-TripWay/assets/167271345/c9cb0e2a-7fb0-4894-b03a-ba78942cb082

Issue#127 將使用者信箱帶入藍新金流結帳畫面

---

payments/service.py
payments/views.py
src/scripts/notice.js
templates/layouts/base-home.html
templates/layouts/base-map.html
templates/layouts/base.html
templates/payments/success.html
templates/payments/upgrade.html
templates/schedules/index.html
templates/schedules/update.html
templates/shared/navbar-home.html
templates/shared/navbar-map.html
templates/shared/navbar.html

1. 依會員等級資格,控制會員升級選項
2. 最高級會員的navbar不會出現會員升級 
3. shedule update的時間選擇統一為24小時制
4. 把base-home / base-map 的script搬到notice.js

Issue#131/ #133 調整會員升級頁面&更改時間選擇為24小時

---

core/urls.py
poetry.lock
src/scripts/app.js
src/scripts/favorite.js
src/scripts/navbar.js
src/scripts/profile/upload.js
static/scripts/route.js
templates/registration/login.html
templates/registration/register.html
templates/schedules/index.html
templates/shared/navbar.html
templates/spots/spot_list.html
templates/trips/index.html

**更新 trip index 切版**
**更新 spots index 切版**
**改變 ADMIN_URL 環境變數名稱**

issue #134 更新 trip/spot index 切版 ＆ 改變 ADMIN_URL 環境變數名稱

---

core/urls.py
payments/service.py
templates/pages/home.html
templates/payments/upgrade.html
templates/shared/navbar.html
templates/spots/add.html

1. Spot add 切版調整
2. home的按鈕變成a標籤

Issue#135 Spot add 切版調整

---

spots/management/commands/seed.py

 issue #139 更新 seed 參數

---

spots/views.py
templates/pages/home.html
templates/trips/index.html

1.每位使用者只能留言一次
2.留過言的景點會將textarea關起來，並顯示:您已經評論過該景點。
3.若要再次留言必須刪除之前的留言

Issue #145 Spot detail 需鎖定一個人針對同一景點僅能留言一次

---

.env.template
spots/management/commands/seed.py
spots/models.py
spots/views.py
static/scripts/map.js
static/scripts/route.js
static/styles/detail.css
templates/schedules/index.html
templates/shared/navbar-map.html
templates/trips/index.html
templates/trips/map.html
trips/views.py

**issue #151 更新 seed 跟 search 資料欄位**
增加圖片欄位
https://github.com/astrocamp/16th-TripWay/assets/162076462/b49a426f-3154-40a0-9494-af0c057c73f5
**issue #150 新增地圖探索小功能**
-  三種圖層切換：
1. 大眾運輸
2. 單車路線
3. 即時路況（塞車情況） 
-  分享當下位置（ ngrok 測試 ）
按下分享按鈕，分享地圖探索網址連結（ 帶經緯度）
https://github.com/astrocamp/16th-TripWay/assets/162076462/eabe4189-1cb4-445d-a498-0f3b5335118b

更新 seed 跟 search 資料欄位 & 新增地圖探索小功能

---

README.md

README更新，大家一起來寫寫

---

members/views.py
notifies/models.py
notifies/views.py
payments/models.py
payments/views.py
static/scripts/notifications.js
templates/notifies/notification_list.html
templates/payments/upgrade.html
trips/views.py

https://github.com/astrocamp/16th-TripWay/assets/162015439/e8d4708c-c45f-4909-b4a0-4d0b3eb5e19d
- 註冊成功時會發送通知
- 會員升級成功時會發送通知
- 創建新行程成功時會發送通知
- 點擊通知頁面的連結會跳轉至相關頁面

Issue #156 小鈴鐺通知事項 -> 註冊成功/會員升級/創建新行程

---

schedules/views.py
spots/views.py
src/scripts/trips/index.js
templates/profile/index.html
templates/shared/navbar-home.html
templates/shared/navbar-map.html
templates/shared/navbar.html
templates/spots/spot_detail.html
templates/spots/spot_list.html
templates/trips/index.html
trips/views.py

**Issue#162**
1. 修正分享共編連結
2. 調整spot index/detail & profile 照片來源，加快Loading速度
https://github.com/astrocamp/16th-TripWay/assets/167271345/d228ccf8-bb7c-4c8c-8253-fb65065e5f66
**Issue#164**
1. spot index / spot detail修正成 未登入也可看 但點擊其他功能時需要登入
https://github.com/astrocamp/16th-TripWay/assets/167271345/7f20297a-81f9-48e0-94b7-71df8d14b11f

Issue#162 & Issue#164 修正分享連結 & 調整spot index 照片來源 & 調整spot 權限

---

templates/pages/about.html
templates/shared/navbar-map.html

**修改 about 頁面**
增加 github 連結 hover

issue #157 修改 about 頁面

---

static/scripts/map.js
static/scripts/route.js
templates/pages/about.html
templates/profile/index.html
templates/shared/navbar-home.html
templates/shared/navbar-map.html
templates/shared/navbar.html
templates/trips/map.html

{ lat: 22.6272784, lng: 120.3014359 }
地圖探索
路線規劃地圖

issue #169 地圖探索 路線規劃地圖 更新預設經緯

---

static/scripts/map.js
templates/schedules/index.html
templates/trips/map.html

可閱讀：不可刪、增
可編輯：可刪、增
```
{% if trip_member.is_editable %}
```

issue #178 增加共編、閱讀者刪減、增加天數權限管控

---

static/scripts/map.js
static/scripts/route.js

**center: { lat: 25.0383401, lng: 121.5060706 }**

issue #181 更新預設經緯

---

templates/profile/index.html

profile RWD 兩個分頁一樣的顯示

---

members/views.py
templates/registration/login.html

更新login_required導向 原目的地
https://github.com/astrocamp/16th-TripWay/assets/167271345/8ef989b5-2c85-4f4c-95bb-2ae31e4cfd4a

Issue #180 更新login_required重新導向

---

members/views.py

https://github.com/astrocamp/16th-TripWay/assets/162015439/111ea049-4278-4e38-a3ce-8e197add18e3
採google跟line第三方登入成功者，也會收到歡迎加入通知

Issue #156 小鈴鐺通知事項 -> 第三方登入用戶的歡迎通知

---

static/scripts/search.js
templates/shared/navbar-home.html
templates/shared/navbar-map.html
templates/shared/navbar.html
templates/spots/spot_list.html

issue #188
**1. 登入加入判斷元素是否存在**
**2. 拔除未使用的 google map api script**
https://github.com/astrocamp/16th-TripWay/assets/162076462/2a7ab863-f23e-43ba-88fa-0b0eb29ef306

issue #188 未登入加入判斷元素是否存在 / 拔除未使用的 google map api script

---

members/urls.py
members/views.py
src/scripts/profile/tab.js
templates/profile/index.html

- 進入頁面預設展開"我的行程"
- 使用下拉式選單選擇排序方法，用get方法傳送下拉式選單
- 預設排序方法是"依建立時間"
[錄製內容 2024-06-12 160801.zip](https://github.com/user-attachments/files/15800781/2024-06-12.160801.zip)

issue #185 個人頁面的行程排序

---

templates/trips/new.html

新增行程表格頁 RWD

---

templates/schedules/index.html

issue #192 schedule編輯的彈跳框 RWD

---

templates/layouts/base-map.html
templates/payments/upgrade.html
templates/schedules/index.html
templates/spots/add.html

1. 付款頁面RWD
2. 調整spot add，當沒有行程時候給一個建立新行程按鈕
3. 調整time picker
https://github.com/astrocamp/16th-TripWay/assets/167271345/84435043-8f4d-494b-a5a5-68caec0ed649

Issue#190 Payment rwd & 調整spot add & 調整time picker

---

src/scripts/message.js
src/tailwind.css
templates/schedules/index.html
templates/schedules/show.html
templates/schedules/update.html

1. update Schedule Index/show/update RWD
2. 調整alert訊息位置置中

Schedule Index RWD 調整

---

templates/pages/about.html

調整 About 頁面 RWD

---

schedules/models.py
schedules/urls.py
schedules/views.py
src/scripts/schedules/index.js
static/scripts/route.js
templates/schedules/index.html

https://github.com/astrocamp/16th-TripWay/assets/162015439/47032e09-5e50-4a14-b9e6-515e0f998e82
行程拖拉功能
地圖圖示會同步更新
備註：有新增景點後，再次進到頁面時還沒點頁籤，地圖就會先顯示路線

 Issue #204 schedule index頁面行程拖拉功能

---

README.md

更新 Demo Day 影片連結
